### ISSUE TITLE
Folders expanding on the original sidebar as well as on the Better Folders one

### ISSUE THREAD

**Issue by deadcombo** [Juby210/better-folders#17] opened 2022-01-10 11:48 UTC
![image](https://user-images.githubusercontent.com/37187650/148761000-7b81ce17-b852-4175-bcb5-5054838d84e3.png)

I believe it is the result of an update, please let me know what diagnostics data I can gather.

Thank you!

**Comment by deadcombo** [comment] 2022-01-13 13:15
It's unfortunately not fixed for me. Console output:

![image](https://user-images.githubusercontent.com/37187650/149336741-09920435-b004-423b-bb05-710a4fc1527e.png)

**Comment by Juby210** [comment] 2022-01-13 21:02
Probably discord changed something.. again

**Comment by SheepCommander** [comment] 2022-01-14 03:45
OOF hope it gets resolved soon. Good work btw

**Comment by Juby210** [comment] 2022-01-16 15:17
btw can't reproduce on latest canary

**Comment by SheepCommander** [comment] 2022-01-17 20:26
@Juby210 Could be specific to windows? In particular I'm w11

![image](https://user-images.githubusercontent.com/66646514/149833278-7a32bb0e-e72e-4dca-92b6-357eba330967.png)
![image](https://user-images.githubusercontent.com/66646514/149833301-7a43c864-6ddd-4711-b874-dc99174055aa.png)

**Comment by Juby210** [comment] 2022-01-17 20:56
resolved by powercord update powercord-org/powercord@12de9dc6c8c35cec730d134731e8cb7c282f0899

**Closed by Juby210** 2022-01-17 20:56 UTC
